###########################################
# Spark - Dremio - Nessie - Iceberg Setup
###########################################

services:
  # Nessie Catalog Server Using In-Memory Store
  catalog:
    image: quay.io/projectnessie/nessie:0.101.3
    ports:
      - "19120:19120"
    networks:
      iceberg-intro-net:

  # Minio Storage Server
  storage:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    command: ["server", "--console-address", ":9001", "/data"]
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      iceberg-intro-net:

  # Minio Client
  mc:
    image: quay.io/minio/mc:RELEASE.2024-11-21T17-21-54Z
    entrypoint: /bin/sh
    command:
      - -c
      - |
        until (/usr/bin/mc config host add minio http://storage:9000 admin password) do echo '...waiting...' && sleep 1; done;
        /usr/bin/mc rm -r --force minio/warehouse;
        /usr/bin/mc mb minio/warehouse;
        /usr/bin/mc mb minio/iceberg;
        /usr/bin/mc policy set public minio/warehouse;
        /usr/bin/mc policy set public minio/iceberg;
        tail -f /dev/null
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    restart: no
    depends_on:
      storage:
        condition: service_healthy
    networks:
      iceberg-intro-net:

  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:25.2
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
    networks:
      iceberg-intro-net:

  # Spark
  spark:
    platform: linux/x86_64
    image: alexmerced/spark35nb:spark3_5_2
    ports:
      - "8080:8080"  # Master Web UI
      - "7077:7077"  # Master Port
      - "8888:8888"  # Notebook
    volumes:
      - ./warehouse:/workspace/warehouse
      - ./notebooks:/workspace/notebooks
      - ./datasets:/workspace/datasets
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    depends_on:
      - storage
      - catalog
    networks:
      iceberg-intro-net:

networks:
  iceberg-intro-net:
